language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y python-opencv
  - pip install -r requirements.txt
script:
  - python setup.py build
virtualenv:
  system_site_packages: true
